# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
gem 'middleman', git: 'git://github.com/middleman/middleman.git'
gem 'middleman-blog', git: 'git://github.com/middleman/middleman-blog.git'

gem 'redcarpet', '~> 3.3', '>= 3.3.3'

# For feed.xml.builder
gem 'builder', '~> 3.0'
